### ISSUE TITLE
there is a bit problem....

### ISSUE THREAD

**Issue by AcNEO** [G07cha/MineflayerAutoAuth#3]
there are some authentication plugin that need to type two time
I mean like this
"/register password password"

any way for it to be 'fixed' ?
or u can try get if error for the first time like it need a repeat ,
 u send register two times, if still need repeated, u use "/register password password" etc

**Comment by G07cha** [comment]
Hey @AcNEO, at the moment there are no functionality available to override register command but we're dispatching `registerRequest` event when `/register` command is received so as a workaround you can remove existing handler for it with `bot.removeAllListeners('registerRequest')` and write your own handler like it's done [here](https://github.com/G07cha/MineflayerAutoAuth/blob/master/index.js#L27-L45).

**Comment by G07cha** [comment]
Feel free to reopen the issue if it doesn't solve the problem.
