### ISSUE TITLE
Download mineflayer-auto-auth

### ISSUE THREAD

**Issue by Donut20** [G07cha/MineflayerAutoAuth#6]
Hello,
I have a download error when I enter the command in cmd: "![erreur](https://user-images.githubusercontent.com/86827956/124250772-7a79af00-db25-11eb-8118-266525b1f775.JPG)".

The error code is as follows:

**Comment by G07cha** [comment]
Seems like you have an issue with your environment and NPM in particular, does installing any other packages work?
If not, you could try searching up the error you're getting and look for a solution.
