### ISSUE TITLE
serverAuth event doesnt work on auto login

### ISSUE THREAD

**Issue by dtdhow** [G07cha/MineflayerAutoAuth#8]
on some servers where auto login works the event serverAuth doesnt work

**Comment by G07cha** [comment]
Do you see any error in the logs? Does the login itself work? If not, what kind of prompt is being sent to the bot from the server?

**Comment by Dolentia** [comment]
Got the same problem when the server auto logins you the serverauth event doesnt work

**Comment by dtdhow** [comment]
The server did not support the serverAuth event
